######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 9 19:16:01 2014
######################################################################

TEMPLATE = app
TARGET = readWriteProject
DEPENDPATH += .
INCLUDEPATH += . ../scidavis ../scidavis/src ../tmp/scidavis

CONFIG        += qt warn_on exceptions opengl thread zlib
CONFIG        += assistant
QT            += opengl qt3support network svg xml
MOC_DIR        = ../tmp/scidavis
OBJECTS_DIR    = ../tmp/scidavis

include(../config.pri)
include(../scidavis/sourcefiles.pri)

QT+=testlib

# Input
HEADERS += readWriteProject.h
SOURCES += readWriteProject.cpp
