######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 9 19:16:01 2014
######################################################################

TEMPLATE = app
TARGET = readWriteProject
DEPENDPATH += .
INCLUDEPATH += . ../libscidavis ../libscidavis/src ../tmp/scidavis ../scidavis
LIBS += -L ../libscidavis -lscidavis


CONFIG        += qt warn_on exceptions opengl thread zlib
CONFIG        += assistant
QT            += opengl qt3support network svg xml
MOC_DIR        = ../tmp/scidavis
OBJECTS_DIR    = ../tmp/scidavis

include(../config.pri)
python {include( ../scidavis/python.pri )}

liborigin {
  LIBS += ../3rdparty/liborigin/liborigin.a
}

QT+=testlib

# Input
HEADERS += readWriteProject.h
SOURCES += readWriteProject.cpp

########### Future code backported from the aspect framework ##################
DEFINES += LEGACY_CODE_0_2_x
INCLUDEPATH += ../libscidavis/src/future
