######################################################################
# Automatically generated by qmake (2.01a) Sa Jun 9 11:27:00 2007
######################################################################

TEMPLATE = app
TARGET = unittests
DEPENDPATH += . ..
INCLUDEPATH += . ..
unix:LIBS += -lcppunit

# units used
HEADERS += \
			  Interval.h \
			  AbstractColumnData.h \
			  DateTimeColumnData.h \
			  DoubleColumnData.h \
			  StringColumnData.h \
			  AbstractDataSource.h \
			  AbstractDateTimeDataSource.h \
			  AbstractDoubleDataSource.h \
			  AbstractStringDataSource.h \
			  IntervalAttribute.h \
			  AbstractFilter.h \
			  CopyThroughFilter.h \
			  String2DoubleFilter.h \
			  Double2StringFilter.h \
			  DateTime2DoubleFilter.h \
			  DateTime2StringFilter.h \
			  Double2DateTimeFilter.h \
			  String2DateTimeFilter.h \
			  Double2MonthFilter.h \
			  Double2DayOfWeekFilter.h \
			  Month2DoubleFilter.h \
			  DayOfWeek2DoubleFilter.h \

SOURCES += \
			  StringColumnData.cpp \
			  DateTimeColumnData.cpp \
			  DoubleColumnData.cpp \
			  AbstractFilter.cpp \
			  String2DateTimeFilter.cpp \

# test cases
HEADERS += \
	assertion_traits.h \

SOURCES += main.cpp \
	IntervalTest.cpp \
	ColumnDataTest.cpp \
	ConversionFilterTest.cpp \

